import Foundation

struct LunarComic: Codable {
	let id: UUID
	var Code: String
	var AlternateLunarCode: String
	var Title: String
	var MainDesc: String
	var IssueNumber: Int
	var MaxIssue: Double
	var ItemCategory: Int
	var ProductCategory: String
	var SeriesCode: Int
	var Retail: Double
	var DiscountCode: String
	var Publisher: String
	var UPC: Int
	var ISBN: Int
	var EAN: Int
	var Writer: [String]
	var Artist: [String]
	var CoverArtist: String
	var InitialOrderDue: String
	var FOCDate: String
	var InStoreDate: String
	var ParentCode: String
	var PageNumber: Int
	var NumberOfPages: Int
	var UnitWeight: Double
	var Mature: Bool
	var Adult: Bool
	var O_A: Bool
	var OrderFormNotes: String
	var Description: String
	var Color: String
	var VariantType: String
	var VariantDescription: String
	var VariantNumber: Int
	var Printing: Int
	var CoverType: String
	var PublishingGroup: String
	var ImprintCode: String
	var SubImprintGroup: String
	var FormatCode: String
	var PaperCode: String
	var CoverCode: String
	var BindingCode: String
	var TrimCode: String
	var TrimSize: String
	var CartonCount: Int
	var Rating: String
	var TradeDress: String
	var Popup: String
	var Sequence: String
	var PublisherCode: String
	var T_Number: String
	var PublisherSeriesCode: String
	var ImageUrl: URL
	var Returnable: String
	var ReturnWindow: String
}

struct DiamondComic: Codable {
	let id: UUID
	var code: String
	var stock_no: Int
	var parent_item_no_alt: String
	var bounce_use_item: String
	var full_title: String
	var main_desc: String
	var variant_desc: String
	var series_code: Int
	var issue_no: Int
	var issue_seq_no: Int
	var volume_tag: String
	var max_issue: Float
	var price: Float
	var publisher: String
	var upc_no: Int
	var short_isbn_no: Int
	var ean_no: Int
	var cards_per_pack: Int
	var pack_per_box: Int
	var box_per_case: Int
	var discount_code: String
	var increment: String
	var prnt_date: String
	var FOC_vender: String
	var ship_date: String
	var srp: Float
	var catergory: Int
	var genre: String
	var brand_code: String
	var mature: String
	var adult: String
	var oa: String
	var caut1: String
	var caut2: String
	var caut3: String
	var resol: String
	var note_price: String
	var order_from_notes: String
	var page: Int
	var writer: [String]
	var artist: [String]
	var cover: [String]
	var colorist: [String]
	var alliance_sku: Int
	var FOC_date: String
	var offered_date: String
	var number_of_pages: Int
	var unit_weight: Float
	var unit_length: Float
	var unit_width: Float
	var unit_height: Float
	var case_weight: Float
	var case_length: Float
	var case_width: Float
	var case_height: Float
}
